name: Run the tests on pull requests

on:
  pull_request:
    branches:
      - main

jobs:
  run-pytest:
    name: 'run pytest tests'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      JENKINS_USERNAME: ${{ secrets.ADMIN_USERNAME }}
      JENKINS_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
      JENKINS_HOST: localhost
      JENKINS_PORT: 8080
      BROWSER_NAME: chrome
      BROWSER_OPTIONS_CHROME: --remote-allow-origins=*;--disable-gpu;--no-sandbox;--disable-dev-shm-usage;--headless=new;--window-size=1920,1080

    steps:
      - name: git clone
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: set up python
        uses: actions/setup-python@v5.2.0
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install the code linting and formatting tool Ruff
        run: pip install ruff

      - name: Lint code with Ruff
        run: ruff check --output-format=github --target-version=py312

      - name: prepare jenkins data
        run: |
          cat ${{ github.workspace }}/jenkins_data/jenkins_backup0* > ${{ github.workspace }}/jenkins_backup.tar
          md5sum ${{ github.workspace }}/jenkins_backup.tar

      - name: extract jenkins data and set permission
        run: |
          tar -xvf ./jenkins_backup.tar
          chmod -R 777 ./jenkins_backup/var/jenkins_home
          chmod -R 777 ./.github/

      - name: Docker login
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Docker start
        run: docker run --rm --detach -p 8080:8080 -v ${{ github.workspace }}/jenkins_backup/var/jenkins_home:/var/jenkins_home jenkins/jenkins:2.492.2-lts-jdk17

      - name: Wait for the Jenkins
        run: ./.github/wait-for-jenkins.sh

      - name: check scope of changes
        id: scope_check
        run: ./.github/diff-checker.sh

      - name: pytest run all tests
        if: steps.scope_check.outputs.run_all_tests == 'true'
        run: pytest --alluredir=build/allure-results
        #continue-on-error: true

      - name: pytest run picked tests
        if: steps.scope_check.outputs.run_all_tests == 'false'
        #run: pytest --picked --mode=branch --parent-branch=origin/${{ github.base_ref }}
        run: pytest --alluredir=build/allure-results
        #continue-on-error: true

      - name: Check for Allure results
        if: always()
        run: |
          echo "Listing contents of build/allure-results:"
          ls -R build/allure-results || echo "build/allure-results directory not found or is empty"
          echo "Current working directory: $(pwd)"
          echo "Listing top-level directories:"
          ls

      - name: Get Allure history
        uses: actions/checkout@v4.2.2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: List gh-pages checkout content (after Get Allure history)
        if: always()
        run: |
          echo "Listing contents of ./gh-pages:"
          ls -R gh-pages || echo "gh-pages directory not found after checkout"

      - name: Generate allure report
        uses: simple-elf/allure-report-action@v1.12
        if: always()
        with:
          allure_results: build/allure-results
          gh_pages: gh-pages
          allure_history: allure-history
          #allure_report: allure-report
          #gh_pages: gh-pages
          #ref: gh-pages
          #path: gh-pages
          keep_reports: 30

      - name: List generated report content before publish
        if: always()
        run: |
          echo "Listing contents of ./gh-pages/allure-history (should be the new report):"
          ls -R gh-pages/allure-history || echo "gh-pages/allure-history not found before publish"

      - name: Commit allure_report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: gh-pages/allure-history

      - name: Attach screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: ${{ github.workspace }}/screenshots
